name: Issue
description: Report an issue or request a feature.
assignees:
  - CodyCBakerPhD
projects:
  - dandi-cache/1
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or feature request.
    validations:
      required: true
